#!/usr/bin/env bash

#----------------------------------------------------------------------------
# Gentoo Update
# Copyright (C) 2015 Nathan Shearer
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 as published by
# the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to:
#   The Free Software Foundation Inc.
#   51 Franklin Street
#   Fifth Floor
#   Boston, MA
#   02110-1301
#   USA

NAME="Gentoo Update"
CODENAME="gentooupdate"
COPYRIGHT="Copyright (C) 2015 Nathan Shearer"
VERSION="1.0.0.0"

# \brief Aborts the update if there is any news
function gentooupdate_abort_if_news
{
	NEWS=`eselect news count`
	if [ $NEWS -ne 0 ]; then
		printf "This update was aborted because there is unread news:\n\n" >>"$TMP"/news.email
		eselect news list >>"$TMP"/news.email
		gentooupdate_email $EMAIL_ERROR "$HOSTNAME: update aborted on $NOW" "$TMP"/news.email
		gentooupdate_exit 1 "Update aborted because there is unread news"
	fi
}

# \brief Ensures dependencies are present
# \param $@ The dependencies to check for
function gentooupdate_check_dependencies
{
	for TOOL in "$@"; do
		if ! type "$TOOL" >/dev/null 2>/dev/null; then
			echo "$CODENAME: \"$TOOL\" is required for this application to work correctly." >&2
			exit
		fi
	done
}

# \brief Cleans the system by removing packages that are not associated with explicitly merged packages
function gentooupdate_depclean
{
	echo "gentooupdate_depclean" "$@" >> "$LOG"
	local NOW=`date --rfc-3339=seconds`
	local FAIL=0
	
	rm -f "$TMP"/depclean.log
	emerge --depclean >>"$TMP"/depclean.log 2>>"$TMP"/depclean.log
	if [ $? -ne 0 ]; then
		printf "The \"emerge --depclean\" operation failed. Log is included below:\n\n" >>"$TMP"/depclean.email
		cat "$TMP"/depclean.log >>"$TMP"/depclean.email
		gentooupdate_email $EMAIL_ERROR "$HOSTNAME: update failed on $NOW" "$TMP"/depclean.email
		gentooupdate_exit 4 "The \"emerge --depclean\" operation failed"
	fi
}

# \brief Sends an email
# \param $1 The e-mail address
# \param $2 The subject
# \param $3 The containing the message
function gentooupdate_email
{
	echo "gentooupdate_email" "$@" >> "$LOG"
	if [ "$1" != "" ]; then
		cat "$3" | mail -s "$2" "$1"
	fi
}

# \brief Cleans up the environment and exits
# \param $1 The exit code
# \param $2 The exit message
#
# If DEBUG=true then temporary files are not deleted.
function gentooupdate_exit
{
	#echo "gentooupdate_exit" "$@" >>"$LOG"
	if $EXITING; then return; fi
	EXITING=true
	local EXIT="$1"
	local MESSAGE="$2"
	if [ "$EXIT" = "" ]; then
		EXIT=0
	fi
	if [ "$MESSAGE" = "" ]; then
		MESSAGE="An unrecoverable error has occurred"
	fi
	if ! $DEBUG; then
		rm -rf "$TMP"
	else
		printf "Debug mode is enabled. Temporary files in \"$TMP\" will *not* be deleted.\n"
	fi
	case $EXIT in
		0) exit;;
		*) echo "$CODENAME: $MESSAGE" >&2; exit $EXIT;;
	esac
}

# \brief Displays the help and exits the program
function gentooupdate_help
{
	printf "$NAME $VERSION\n"
	printf "$COPYRIGHT\n\n"
	printf "This script automatically updates Gentoo Linux.\n\n"
	printf "Usage:\n"
	printf "  $CODENAME [options]\n"
	printf "Options:\n"
	printf "  -h\n"
	printf "    Display this help message and exit.\n"
	printf "  -n N\n"
	printf "    Sets the niceness to N (default 0).\n"
	printf "Examples:\n"
	printf "  $CODENAME -h\n"
	printf "  $CODENAME -n 5\n"
	exit
}

# \brief Logs messages to syslog with logger
# \param $1 Only log this message if $VERBOSE is greater than or equal to $1
# \param $2 The message that will be logged
function gentooupdate_log
{
	if [ $VERBOSE -ge $1 ]; then
		logger "$CODENAME: $2"
	fi
}

# \brief The main function of this script
function gentooupdate_main
{
	echo "gentooupdate_email" "$@" >> "$LOG"
	local NOW=`date --rfc-3339=seconds`
	local FAIL=0
	
	gentooupdate_sync
	gentooupdate_update
	gentooupdate_represerve
	gentooupdate_depclean
	gentooupdate_revdep
	
	printf "The update completed successfully.\n" > "$TMP"/success.email
	gentooupdate_email $EMAIL_LOG "$HOSTNAME: update completed successfully on $NOW" "$TMP"/success.email
}

# \brief Rebuilds packages with preserved libraries
function gentooupdate_represerve
{
	echo "gentooupdate_represerve" "$@" >> "$LOG"
	local NOW=`date --rfc-3339=seconds`
	local FAIL=0
	
	gentooupdate_abort_if_news

	rm -f "$TMP"represerve
	emerge @preserved-rebuild >>"$TMP"/represerve.log 2>>"$TMP"/represerve.log
	if [ $? -ne 0 ]; then
		printf "The \"emerge @preserved-rebuild\" operation failed. Log is included below:\n\n" >>"$TMP"/represerve.email
		cat "$TMP"/represerve.log >>"$TMP"/represerve.email
		gentooupdate_email $EMAIL_ERROR "$HOSTNAME: update failed on $NOW" "$TMP"/represerve.email
		gentooupdate_exit 3 "The \"emerge @preserved-rebuild\" operation failed"
	fi
}

# \brief Re-emerge broken binaries and shared libraries
function gentooupdate_revdep
{
	echo "gentooupdate_revdep" "$@" >> "$LOG"
	local NOW=`date --rfc-3339=seconds`
	local FAIL=0
	
	rm -f "$TMP"/revdep-rebuild.log
	revdep-rebuild >>"$TMP"/revdep-rebuild.log 2>>"$TMP"/revdep-rebuild.log
	if [ $? -ne 0 ]; then
		printf "The \"revdep-rebuild\" operation failed. Log is included below:\n\n" >>"$TMP"/revdep-rebuild.email
		cat "$TMP"/revdep-rebuild.log >>"$TMP"/revdep-rebuild.email
		gentooupdate_email $EMAIL_ERROR "$HOSTNAME: update failed on $NOW" "$TMP"/revdep-rebuild.email
		gentooupdate_exit 5 "The \"revdep-rebuild\" operation failed"
	fi
}

# \brief Synchronizes portage repositories
function gentooupdate_sync
{
	echo "gentooupdate_sync" "$@" >> "$LOG"
	local NOW=`date --rfc-3339=seconds`
	local FAIL=0
	
	gentooupdate_abort_if_news

	rm -f "$TMP"/sync.log
	emerge --sync >>"$TMP"/sync.log 2>>"$TMP"/sync.log
	if [ $? -ne 0 ]; then
		printf "The \"emerge --sync\" operation failed. Log is included below:\n\n" >>"$TMP"/sync.email
		cat "$TMP"/sync.log >>"$TMP"/sync.email
		gentooupdate_email $EMAIL_ERROR "$HOSTNAME: update failed on $NOW" "$TMP"/sync.email
		gentooupdate_exit 2 "The \"emerge --sync\" operation failed"
	fi
}

# \brief Update packages
function gentooupdate_update
{
	echo "gentooupdate_update" "$@" >> "$LOG"
	local NOW=`date --rfc-3339=seconds`
	local FAIL=0
	
	gentooupdate_abort_if_news

	rm -f "$TMP"/update.log
	emerge -uDN --with-bdeps=y world >>"$TMP"/update.log 2>>"$TMP"/update.log
	if [ $? -ne 0 ]; then
		printf "The \"emerge -uDN --with-bdeps=y world\" operation failed. Log is included below:\n\n" >>"$TMP"/update.email
		cat "$TMP"/update.log >>"$TMP"/update.email
		gentooupdate_email $EMAIL_ERROR "$HOSTNAME: update failed on $NOW" "$TMP"/update.email
		gentooupdate_exit 3 "The \"emerge -uDN --with-bdeps=y world\" operation failed"
	fi
}

# \brief Prints out the version and copyright and exits this program
function gentooupdate_version
{
	printf "$NAME $VERSION $COPYRIGHT\n"
	exit
}

#------------------------------------------------------------------------------
# default configuration
#
EMAIL_ERROR=""
EMAIL_LOG=""
DEBUG=false
NICE=0
TMP="/tmp"

#------------------------------------------------------------------------------
# config files
#
if [ -r /etc/$CODENAME.conf ]; then
	. /etc/$CODENAME.conf
fi
if [ -r ~/.$CODENAME.conf ]; then
	. ~/.$CODENAME.conf
fi

#------------------------------------------------------------------------------
# command line arguments
#
while getopts "hn:" OPTION; do
	case "$OPTION" in
		"h") gentooupdate_help;;
		"n") NICE="$OPTARG";;
		*) gentooupdate_help;;
	esac
done
shift $(( $OPTIND - 1 ))

#------------------------------------------------------------------------------
# prepare environment
#
EXITING=false
trap gentooupdate_exit EXIT SIGHUP SIGINT SIGQUIT SIGABRT SIGKILL SIGTERM
TMP="$TMP/$CODENAME.$$"
mkdir -p "$TMP"
LOG="$TMP/log"
touch "$LOG"
renice $NICE $$ >>"$LOG" 2>>"$LOG"

#------------------------------------------------------------------------------
# begin execution
#
gentooupdate_main
